# Generated by Django 4.0 on 2022-02-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_platform_url',
            field=models.URLField(default='np', max_length=500, verbose_name='Podcast Platform Url'),
            preserve_default=False,
        ),
    ]
