# Generated by Django 4.0 on 2022-03-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_podcast_podcast_platform_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='podcast_url',
        ),
    ]
